baseURL = "https://example.com"
locale = "ja"
title = "my.blog"
enableRobotsTXT = true

[pagination]
  pagerSize = 12

[params]
  description = "tech notes, ideas, and occasional rants about the web."
  author = "my.blog"

[taxonomies]
  tag = "tags"

[markup.highlight]
  noClasses = false

[markup.goldmark.renderer]
  unsafe = true
