baseURL = "https://matsuoshi.github.io"
locale = "ja"
title = "monaurallog"
enableRobotsTXT = true

[pagination]
  pagerSize = 12

[params]
  description = "モノラルログ: matsuo のざっくりしたブログです"
  author = "matsuoshi"

[taxonomies]
  tag = "tags"

[markup.highlight]
  noClasses = false

[markup.goldmark.renderer]
  unsafe = true
