name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          cache: yarn

      - name: install dependencies
        run: yarn --frozen-lockfile

      - name: build and export
        run: yarn build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: matsuoshi/matsuoshi.github.io
          publish_branch: main
          publish_dir: ./dist
